#!/usr/bin/env python
"""frida_time_hook.py - 覆写时间/随机源，让未修改的二进制在指定时间下自己产出 flag。

宿主侧脚本（stdlib only；运行模式才 import frida）。
实战背景：snake.exe 用 time.time() 播种 srand——枚举候选 unix 时间 + frida hook
把时钟钉在候选值上，二进制自己算出正确答案。本脚本生成并运行对应 hook。

三类时间源（--source）：
  win    kernel32/kernelbase!GetSystemTimeAsFileTime + GetSystemTimePreciseAsFileTime
  linux  libc time / gettimeofday / clock_gettime（默认只覆写 CLOCK_REALTIME，
         --all-clocks 连 CLOCK_MONOTONIC 一起钉——可能影响 sleep/超时逻辑）
  java   java.lang.System.currentTimeMillis（attach 模式，Android 用 --device usb）

用法：
  # 只生成脚本（离线审计/手工投递）
  python frida_time_hook.py --source win --value 1700000000 --list
  # 单值运行：Windows 目标挂起式 spawn（hook 先于入口点生效，stdout 捕获）
  python frida_time_hook.py --source win --value 1700000000 --spawn ./snake.exe --selfcheck
  # 枚举候选时间：逐个 spawn，stdout 命中 --pattern（默认 flag{...}）即停
  python frida_time_hook.py --source win --enumerate 1699990000:1700001000 \
      --spawn ./snake.exe --pattern "KEY=\\d+"
  # attach 到运行中进程（linux/java 的主路径）
  python frida_time_hook.py --source java --value 1700000000 --attach com.app --device usb

--value 接受："1700000000"（unix 秒）/ "unix:1700000000" / "filetime:133444736000000000"；
裸整数 >= 1e15 自动按 FILETIME 换算成 unix 秒。FILETIME = (unix+11644473600)*10^7。

frida 17 差异（实测 17.18.0）：
  - Device 无 output()：spawn 的 piped stdio 读不到 → Windows spawn 走
    CreateProcessW(CREATE_SUSPENDED) + 匿名管道捕获（attach 后 ResumeThread）。
  - JS 侧 Module.getGlobalExportByName 取代 findGlobalExportByName；
    findExportByName(null, ...) 仍可用——生成的 JS 三层兜底。
  - 非 Windows 宿主 spawn 退回 device.spawn(stdio=inherit)：输出直接上屏，
    --pattern 匹配不可用（会 warning）。

exit codes: 0 ok / 1 用法或 IO 错误 / 2 闸门拦截（frida 缺失、目标不存在、
组合非法、平台不符）。输出一律 JSON。生成物落盘 --out（默认
~/.kimi-work/frida_time_hook/<ts>/），便于 ledger.py 引证。
"""
from __future__ import annotations

import argparse
import ctypes
import json
import os
import re
import sys
import threading
import time as _time
from pathlib import Path

for _s in (sys.stdout, sys.stderr):
    _s.reconfigure(encoding="utf-8", errors="replace")

IS_WINDOWS = os.name == "nt"
DEFAULT_OUT_BASE = Path(os.path.expanduser("~")) / ".kimi-work" / "frida_time_hook"
DEFAULT_PATTERN = r"(?i)flag\{[^}]{1,128}\}"
FILETIME_EPOCH_DELTA = 11644473600  # 1601-01-01 -> 1970-01-01, seconds

VENV_HINT = ("frida 不可导入。本机工具栈："
             "~/Desktop/src/re-tools-venv/Scripts/python.exe "
             "frida_time_hook.py ...（venv 内 frida 17.18.0）")

# ---------------------------------------------------------------------------
# JS templates（__TOKEN__ 占位，生成时替换；frida 17 GumJS）
# ---------------------------------------------------------------------------

_JS_FIND_EXPORT = r"""
  function findExport(name, moduleName) {
    if (moduleName) {
      if (typeof Module.getExportByName === 'function') {
        try { var p = Module.getExportByName(moduleName, name); if (p) return p; } catch (e) {}
      }
      try { return Module.findExportByName(moduleName, name); } catch (e) { return null; }
    }
    if (typeof Module.getGlobalExportByName === 'function') {          // frida 17
      try { var g = Module.getGlobalExportByName(name); if (g) return g; } catch (e) {}
    }
    if (typeof Module.findGlobalExportByName === 'function') {         // frida 16
      try { var g2 = Module.findGlobalExportByName(name); if (g2) return g2; } catch (e) {}
    }
    try { return Module.findExportByName(null, name); } catch (e) { return null; }
  }
"""

WIN_JS = r"""// frida_time_hook [win] generated by re-dynamic/scripts/frida_time_hook.py
// pins GetSystemTimeAsFileTime / GetSystemTimePreciseAsFileTime to unix __UNIX__
'use strict';
(function () {
  var UNIX = __UNIX__;
  var FT_LO = __FT_LO__;
  var FT_HI = __FT_HI__;
""" + _JS_FIND_EXPORT + r"""
  var hooked = [];
  var seen = {};
  function hookFiletime(name) {
    var addrs = [];
    ['kernelbase.dll', 'kernel32.dll'].forEach(function (m) {
      var a = findExport(name, m);
      if (a && !seen[a.toString()]) { seen[a.toString()] = true; addrs.push(a); }
    });
    if (addrs.length === 0) {
      var g = findExport(name, null);
      if (g && !seen[g.toString()]) { seen[g.toString()] = true; addrs.push(g); }
    }
    addrs.forEach(function (addr) {
      Interceptor.attach(addr, {
        onEnter: function (args) { this.buf = args[0]; },
        onLeave: function () {
          if (this.buf && !this.buf.isNull()) {
            this.buf.writeU32(FT_LO >>> 0);
            this.buf.add(4).writeU32(FT_HI >>> 0);
          }
          send({ t: 'hit', api: name, unix: UNIX });
        }
      });
      hooked.push(name + '@' + addr);
    });
    return addrs.length ? addrs[0] : null;
  }

  var primary = hookFiletime('GetSystemTimeAsFileTime');
  hookFiletime('GetSystemTimePreciseAsFileTime');
  if (hooked.length === 0) { send({ t: 'error', error: 'no filetime api resolvable' }); return; }
  send({ t: 'installed', source: 'win', hooked: hooked, unix: UNIX });

  if (__SELFCHECK__) {
    try {
      var f = new NativeFunction(primary, 'void', ['pointer']);
      var buf = Memory.alloc(8);
      f(buf);
      var lo = buf.readU32();
      var hi = buf.add(4).readU32();
      send({ t: 'selfcheck', api: 'GetSystemTimeAsFileTime',
             observed_lo: lo, observed_hi: hi,
             expected_lo: FT_LO >>> 0, expected_hi: FT_HI >>> 0,
             ok: (lo === (FT_LO >>> 0)) && (hi === (FT_HI >>> 0)) });
    } catch (e) { send({ t: 'selfcheck', ok: false, error: '' + e }); }
  }
})();
"""

LINUX_JS = r"""// frida_time_hook [linux] generated by re-dynamic/scripts/frida_time_hook.py
// pins time/gettimeofday/clock_gettime to unix __UNIX__
'use strict';
(function () {
  var UNIX = __UNIX__;
  var ALL_CLOCKS = __ALL_CLOCKS__;
  var PS = Process.pointerSize;
""" + _JS_FIND_EXPORT + r"""
  function writeLong(buf, v) { if (PS === 8) buf.writeS64(v); else buf.writeS32(v); }
  var hooked = [];

  var pTime = findExport('time', null);
  if (pTime) {
    Interceptor.attach(pTime, {
      onEnter: function (args) { this.tloc = args[0]; },
      onLeave: function (retval) {
        retval.replace(ptr(UNIX));
        if (this.tloc && !this.tloc.isNull()) writeLong(this.tloc, UNIX);
        send({ t: 'hit', api: 'time', unix: UNIX });
      }
    });
    hooked.push('time');
  }
  var pGtod = findExport('gettimeofday', null);
  if (pGtod) {
    Interceptor.attach(pGtod, {
      onEnter: function (args) { this.tv = args[0]; },
      onLeave: function () {
        if (this.tv && !this.tv.isNull()) {
          writeLong(this.tv, UNIX);
          writeLong(this.tv.add(PS), 0);
        }
        send({ t: 'hit', api: 'gettimeofday', unix: UNIX });
      }
    });
    hooked.push('gettimeofday');
  }
  var pCgt = findExport('clock_gettime', null);
  if (pCgt) {
    Interceptor.attach(pCgt, {
      onEnter: function (args) { this.clk = args[0].toInt32(); this.ts = args[1]; },
      onLeave: function () {
        if (!ALL_CLOCKS && this.clk !== 0) return;  // 只钉 CLOCK_REALTIME
        if (this.ts && !this.ts.isNull()) {
          writeLong(this.ts, UNIX);
          writeLong(this.ts.add(PS), 0);
        }
        send({ t: 'hit', api: 'clock_gettime', unix: UNIX });
      }
    });
    hooked.push('clock_gettime');
  }
  if (hooked.length === 0) { send({ t: 'error', error: 'no libc time api resolvable' }); return; }
  send({ t: 'installed', source: 'linux', hooked: hooked, unix: UNIX });

  if (__SELFCHECK__ && pTime) {
    try {
      var tf = new NativeFunction(pTime, 'long', ['pointer']);
      var observed = tf(NULL);
      send({ t: 'selfcheck', api: 'time', observed_unix: observed,
             expected_unix: UNIX, ok: observed === UNIX });
    } catch (e) { send({ t: 'selfcheck', ok: false, error: '' + e }); }
  }
})();
"""

JAVA_JS = r"""// frida_time_hook [java] generated by re-dynamic/scripts/frida_time_hook.py
// pins System.currentTimeMillis to unix __UNIX__ (__MS__ ms)
'use strict';
Java.perform(function () {
  var MS = __MS__;
  var System = Java.use('java.lang.System');
  System.currentTimeMillis.implementation = function () {
    send({ t: 'hit', api: 'System.currentTimeMillis', ms: MS });
    return MS;
  };
  send({ t: 'installed', source: 'java', hooked: ['java.lang.System.currentTimeMillis'], ms: MS });
  if (__SELFCHECK__) {
    try {
      var observed = System.currentTimeMillis();
      send({ t: 'selfcheck', api: 'currentTimeMillis',
             observed_ms: observed, expected_ms: MS, ok: observed === MS });
    } catch (e) { send({ t: 'selfcheck', ok: false, error: '' + e }); }
  }
});
"""

SOURCES = ("win", "linux", "java")


# ---------------------------------------------------------------------------
# value / template helpers
# ---------------------------------------------------------------------------

def parse_time_value(text: str) -> int:
    """-> unix seconds. Accepts unix: / filetime: / ft: prefixes; bare int
    >= 1e15 is treated as FILETIME and converted."""
    t = text.strip().lower()
    for pre in ("filetime:", "ft:"):
        if t.startswith(pre):
            ft = int(t[len(pre):], 0)
            return ft // 10_000_000 - FILETIME_EPOCH_DELTA
    if t.startswith("unix:"):
        return int(t[5:], 0)
    v = int(t, 0)
    if v >= 10**15:
        return v // 10_000_000 - FILETIME_EPOCH_DELTA
    return v


def unix_to_filetime(unix: int) -> int:
    return (unix + FILETIME_EPOCH_DELTA) * 10_000_000


def parse_enumerate(spec: str) -> list[int]:
    """"S:E[:STEP]" -> inclusive unix-second list (each item parse_time_value)."""
    parts = spec.split(":")
    # unix:/filetime: prefixes break naive split; only plain ints allowed here
    if len(parts) not in (2, 3):
        raise ValueError("--enumerate 需要 START:END[:STEP]（纯整数 unix 秒）")
    start, end = int(parts[0], 0), int(parts[1], 0)
    step = int(parts[2], 0) if len(parts) == 3 else 1
    if step == 0 or (end - start) * step < 0:
        raise ValueError("--enumerate 步长与区间方向不符")
    out, v = [], start
    while (v <= end if step > 0 else v >= end):
        out.append(v)
        v += step
    if not out:
        raise ValueError("--enumerate 区间为空")
    return out


def build_script(source: str, unix: int, selfcheck: bool = False,
                 all_clocks: bool = False) -> str:
    ft = unix_to_filetime(unix)
    repl = {
        "__UNIX__": str(unix),
        "__FT_LO__": str(ft & 0xFFFFFFFF),
        "__FT_HI__": str((ft >> 32) & 0xFFFFFFFF),
        "__MS__": str(unix * 1000),
        "__SELFCHECK__": "1" if selfcheck else "0",
        "__ALL_CLOCKS__": "1" if all_clocks else "0",
    }
    tmpl = {"win": WIN_JS, "linux": LINUX_JS, "java": JAVA_JS}[source]
    js = tmpl
    for k, v in repl.items():
        js = js.replace(k, v)
    leftover = re.findall(r"__[A-Z][A-Z0-9_]*__", js)
    if leftover:
        raise RuntimeError(f"模板替换残留: {sorted(set(leftover))}")
    return js


def emit(obj: dict) -> None:
    print(json.dumps(obj, ensure_ascii=False))


# ---------------------------------------------------------------------------
# windows suspended spawn with piped stdio (frida 17 has no Device.output)
# ---------------------------------------------------------------------------

class WinSpawn:
    def __init__(self):
        self.pid = 0
        self.h_process = None
        self.h_thread = None
        self._k32 = None
        self._out_chunks: list[bytes] = []
        self._err_chunks: list[bytes] = []
        self._readers: list[threading.Thread] = []

    def resume(self) -> None:
        self._k32.ResumeThread(self.h_thread)

    def wait(self, timeout_s: float) -> int:
        """-> exit code, or None on timeout (process killed)."""
        k32 = self._k32
        r = k32.WaitForSingleObject(self.h_process, int(timeout_s * 1000))
        if r == 0x00000102:  # WAIT_TIMEOUT
            k32.TerminateProcess(self.h_process, 0xFFFF)
            k32.WaitForSingleObject(self.h_process, 5000)
            return None
        code = ctypes.wintypes.DWORD()
        k32.GetExitCodeProcess(self.h_process, ctypes.byref(code))
        return code.value

    def drain(self, timeout_s: float = 5.0) -> tuple[str, str]:
        for t in self._readers:
            t.join(timeout_s)
        dec = lambda b: b.decode("utf-8", errors="replace")
        return dec(b"".join(self._out_chunks)), dec(b"".join(self._err_chunks))

    def close(self) -> None:
        k32 = self._k32
        for h in (self.h_thread, self.h_process):
            if h:
                k32.CloseHandle(h)


def _spawn_suspended_win32(exe: str, argv: list[str]) -> WinSpawn:
    import msvcrt
    from ctypes import wintypes as wt

    k32 = ctypes.WinDLL("kernel32", use_last_error=True)
    CREATE_SUSPENDED = 0x00000004
    STARTF_USESTDHANDLES = 0x00000100
    HANDLE_FLAG_INHERIT = 0x00000001
    STD_INPUT_HANDLE = -10 & 0xFFFFFFFF

    class SECURITY_ATTRIBUTES(ctypes.Structure):
        _fields_ = [("nLength", wt.DWORD), ("lpSecurityDescriptor", wt.LPVOID),
                    ("bInheritHandle", wt.BOOL)]

    class STARTUPINFOW(ctypes.Structure):
        _fields_ = [("cb", wt.DWORD), ("lpReserved", wt.LPWSTR), ("lpDesktop", wt.LPWSTR),
                    ("lpTitle", wt.LPWSTR), ("dwX", wt.DWORD), ("dwY", wt.DWORD),
                    ("dwXSize", wt.DWORD), ("dwYSize", wt.DWORD),
                    ("dwXCountChars", wt.DWORD), ("dwYCountChars", wt.DWORD),
                    ("dwFillAttribute", wt.DWORD), ("dwFlags", wt.DWORD),
                    ("wShowWindow", wt.WORD), ("cbReserved2", wt.WORD),
                    ("lpReserved2", wt.LPVOID),
                    ("hStdInput", wt.HANDLE), ("hStdOutput", wt.HANDLE),
                    ("hStdError", wt.HANDLE)]

    class PROCESS_INFORMATION(ctypes.Structure):
        _fields_ = [("hProcess", wt.HANDLE), ("hThread", wt.HANDLE),
                    ("dwProcessId", wt.DWORD), ("dwThreadId", wt.DWORD)]

    def make_pipe():
        r, w = wt.HANDLE(), wt.HANDLE()
        sa = SECURITY_ATTRIBUTES(ctypes.sizeof(SECURITY_ATTRIBUTES), None, True)
        if not k32.CreatePipe(ctypes.byref(r), ctypes.byref(w), ctypes.byref(sa), 0):
            raise OSError(ctypes.get_last_error(), "CreatePipe failed")
        k32.SetHandleInformation(r, HANDLE_FLAG_INHERIT, 0)
        return r, w

    r_out, w_out = make_pipe()
    r_err, w_err = make_pipe()

    si = STARTUPINFOW()
    si.cb = ctypes.sizeof(STARTUPINFOW)
    si.dwFlags = STARTF_USESTDHANDLES
    si.hStdInput = k32.GetStdHandle(STD_INPUT_HANDLE)
    si.hStdOutput = w_out
    si.hStdError = w_err
    pi = PROCESS_INFORMATION()

    cmdline = " ".join([f'"{exe}"'] + [a if re.fullmatch(r"[A-Za-z0-9_./:\\-]+", a)
                                       else f'"{a}"' for a in argv])
    ok = k32.CreateProcessW(None, cmdline, None, None, True, CREATE_SUSPENDED,
                            None, None, ctypes.byref(si), ctypes.byref(pi))
    k32.CloseHandle(w_out)
    k32.CloseHandle(w_err)
    if not ok:
        err = ctypes.get_last_error()
        raise OSError(err, f"CreateProcessW failed: {cmdline} (winerror {err})")

    sp = WinSpawn()
    sp.pid = pi.dwProcessId
    sp.h_process = pi.hProcess
    sp.h_thread = pi.hThread
    sp._k32 = k32

    def reader(handle, chunks):
        fd = msvcrt.open_osfhandle(handle, os.O_RDONLY)
        try:
            while True:
                data = os.read(fd, 65536)
                if not data:
                    break
                chunks.append(data)
        except OSError:
            pass
        finally:
            os.close(fd)

    for handle, chunks in ((r_out.value, sp._out_chunks), (r_err.value, sp._err_chunks)):
        t = threading.Thread(target=reader, args=(handle, chunks), daemon=True)
        t.start()
        sp._readers.append(t)
    return sp


# ---------------------------------------------------------------------------
# frida run engine（仅运行模式 import frida）
# ---------------------------------------------------------------------------

def _import_frida():
    try:
        import frida
        return frida
    except ImportError:
        emit({"ok": False, "gate": "frida-missing", "error": VENV_HINT})
        sys.exit(2)


def _get_device(frida, which: str):
    if which == "usb":
        try:
            return frida.get_usb_device(timeout=5)
        except Exception as e:
            emit({"ok": False, "gate": "usb-device-missing", "error": str(e)})
            sys.exit(2)
    return frida.get_local_device()


def run_one(device, js: str, args, spawn_argv: list[str] | None) -> dict:
    """Attach/spawn one target, load script, wait detached/timeout, collect."""
    frida = _import_frida()
    result: dict = {"hits": 0, "messages": [], "installed": None,
                    "selfcheck": None, "js_errors": []}
    detached = threading.Event()

    win_spawn: WinSpawn | None = None
    session = None
    try:
        if spawn_argv is not None:
            if IS_WINDOWS:
                win_spawn = _spawn_suspended_win32(spawn_argv[0], spawn_argv[1:])
                pid = win_spawn.pid
            else:
                pid = device.spawn(spawn_argv[0], argv=spawn_argv[1:], stdio="inherit")
                result["warning"] = ("非 Windows 宿主：stdout 未捕获（inherit 上屏），"
                                     "--pattern 匹配不可用")
            session = device.attach(pid)
            result["pid"] = pid
        else:
            target = args.pid if args.pid is not None else args.attach
            try:
                session = device.attach(target)
            except Exception as e:
                emit({"ok": False, "gate": "attach-failed", "target": str(target),
                      "error": str(e)})
                sys.exit(2)
            result["pid"] = session.pid

        script = session.create_script(js)

        def on_message(message, data):
            if message.get("type") == "error":
                result["js_errors"].append(message.get("description", str(message)))
                return
            payload = message.get("payload") or {}
            if not isinstance(payload, dict):
                return
            kind = payload.get("t")
            if kind == "hit":
                result["hits"] += 1
            elif kind == "installed":
                result["installed"] = payload
            elif kind == "selfcheck":
                result["selfcheck"] = payload
            else:
                result["messages"].append(payload)

        def on_detached(reason, *rest):
            result["detach_reason"] = reason
            detached.set()

        script.on("message", on_message)
        session.on("detached", on_detached)
        script.load()

        if win_spawn is not None:
            win_spawn.resume()
        elif spawn_argv is not None:
            device.resume(pid)

        detached.wait(args.timeout)
        if not detached.is_set():
            result["timeout"] = True
            if spawn_argv is not None:
                try:
                    device.kill(result["pid"])
                except Exception:
                    pass
        # 给 in-flight message 一点时间
        _time.sleep(0.3)

        if win_spawn is not None:
            code = win_spawn.wait(3)
            result["exit_code"] = code
            out, err = win_spawn.drain()
            result["stdout"] = out
            if err.strip():
                result["stderr"] = err
            win_spawn.close()
    except SystemExit:
        raise
    except Exception as e:
        result["fatal"] = f"{type(e).__name__}: {e}"
    finally:
        if session is not None:
            try:
                session.detach()
            except Exception:
                pass
    return result


def check_pattern(result: dict, pattern: re.Pattern | None) -> str | None:
    if pattern is None:
        return None
    m = pattern.search(result.get("stdout") or "")
    return m.group(0) if m else None


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="frida 时间源覆写：生成/运行 hook，让二进制在指定时间下自己产出答案",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", required=True, choices=SOURCES + ("all",),
                    help="时间源家族：win=GetSystemTimeAsFileTime / linux=time,"
                         "gettimeofday,clock_gettime / java=System.currentTimeMillis；"
                         "all 仅 --list（三类脚本一次全生成）")
    ap.add_argument("--value", help="覆写值：unix 秒 / unix:N / filetime:N（裸整数>=1e15 按 FILETIME）")
    ap.add_argument("--values", help="逗号分隔候选值列表（逐个运行，需 --spawn）")
    ap.add_argument("--enumerate", dest="enum",
                    help="候选区间 START:END[:STEP]（unix 秒，含端点；需 --spawn）")

    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--list", action="store_true", help="只生成 JS 脚本，不运行")
    mode.add_argument("--spawn", metavar="EXE", help="spawn 目标（挂起式，hook 先于入口生效）")
    mode.add_argument("--attach", metavar="NAME", help="attach 到运行中进程（按名字）")
    mode.add_argument("--pid", type=int, help="attach 到运行中进程（按 PID）")

    ap.add_argument("--arg", action="append", default=[], dest="target_args",
                    help="传给 spawn 目标的参数（可重复；以 - 开头的参数用 --arg=-X 形式）")
    ap.add_argument("--device", choices=["local", "usb"], default="local",
                    help="local（默认）/ usb（Android，java 源常用）")
    ap.add_argument("--timeout", type=float, default=30.0,
                    help="单次运行最长等待秒数（默认 30；超时即 kill）")
    ap.add_argument("--pattern", default=DEFAULT_PATTERN,
                    help=f"spawn 模式 stdout 命中即报/即停的正则（默认 {DEFAULT_PATTERN!r}）")
    ap.add_argument("--selfcheck", action="store_true",
                    help="生成 JS 内嵌自检：装钩后直接调被钩函数验证返回值")
    ap.add_argument("--all-clocks", action="store_true",
                    help="linux：连 CLOCK_MONOTONIC 一起覆写（可能影响 sleep/超时）")
    ap.add_argument("--out", help=f"生成物目录（默认 {DEFAULT_OUT_BASE}/<时间戳>/）")

    args = ap.parse_args()

    # ---- value set ----
    values: list[int] = []
    try:
        if args.value is not None:
            values = [parse_time_value(args.value)]
        elif args.values:
            values = [parse_time_value(v) for v in args.values.split(",") if v.strip()]
        elif args.enum:
            values = parse_enumerate(args.enum)
    except ValueError as e:
        emit({"ok": False, "error": str(e)})
        return 1
    if not values:
        emit({"ok": False,
              "error": "必须给 --value / --values / --enumerate 之一"})
        return 1

    # ---- gates (exit 2) ----
    if args.source == "all" and not args.list:
        emit({"ok": False, "gate": "all-needs-list",
              "error": "--source all 仅用于 --list；运行模式必须指定单一时间源"})
        return 2
    if len(values) > 1 and not args.spawn:
        emit({"ok": False, "gate": "enumerate-needs-spawn",
              "error": "--values/--enumerate 逐个重跑目标，必须配 --spawn"})
        return 2
    if args.spawn and not Path(args.spawn).is_file():
        emit({"ok": False, "gate": "spawn-target-missing",
              "error": f"spawn 目标不存在: {args.spawn}"})
        return 2
    if args.source == "java" and args.spawn:
        emit({"ok": False, "gate": "java-spawn-unsupported",
              "error": "java 源请用 --attach/--pid（Android 配 --device usb）"})
        return 2
    if args.source == "win" and not args.list and args.device == "local" and not IS_WINDOWS:
        emit({"ok": False, "gate": "platform-mismatch",
              "error": "win 源只能 hook Windows 目标（本宿主非 Windows）"})
        return 2

    out_dir = Path(args.out) if args.out else (
        DEFAULT_OUT_BASE / _time.strftime("%Y%m%d-%H%M%S"))
    out_dir.mkdir(parents=True, exist_ok=True)

    pattern = None
    if args.pattern:
        try:
            pattern = re.compile(args.pattern)
        except re.error as e:
            emit({"ok": False, "error": f"--pattern 正则非法: {e}"})
            return 1

    # ---- list mode ----
    if args.list:
        scripts = []
        sources = SOURCES if args.source == "all" else (args.source,)
        for src in sources:
            js = build_script(src, values[0], selfcheck=args.selfcheck,
                              all_clocks=args.all_clocks)
            path = out_dir / f"hook_{src}.js"
            path.write_text(js, encoding="utf-8")
            scripts.append({"source": src, "path": str(path), "bytes": len(js)})
        emit({"ok": True, "mode": "list", "value_unix": values[0],
              "filetime": unix_to_filetime(values[0]) if args.source in ("win", "all") else None,
              "out_dir": str(out_dir), "scripts": scripts})
        return 0

    # ---- run mode ----
    spawn_argv = [args.spawn] + list(args.target_args) if args.spawn else None
    runs = []
    matched = None
    for i, v in enumerate(values):
        js = build_script(args.source, v, selfcheck=args.selfcheck,
                          all_clocks=args.all_clocks)
        js_path = out_dir / f"hook_{args.source}_{v}.js"
        js_path.write_text(js, encoding="utf-8")

        device = _get_device(_import_frida(), args.device)
        r = run_one(device, js, args, spawn_argv)
        r["value_unix"] = v
        r["script"] = str(js_path)
        r["pattern_match"] = check_pattern(r, pattern)
        runs.append(r)
        if r["pattern_match"]:
            matched = {"value_unix": v, "match": r["pattern_match"]}
            break
        if r.get("fatal"):
            break

    ok = all(not r.get("fatal") for r in runs)
    out = {"ok": ok, "mode": "run", "source": args.source,
           "target": args.spawn or args.attach or args.pid,
           "out_dir": str(out_dir), "runs": runs, "matched": matched}
    if len(runs) == 1:
        # 单值运行：把关键字段提到顶层方便人读
        r = runs[0]
        for k in ("installed", "selfcheck", "hits", "exit_code", "detach_reason",
                  "timeout", "pattern_match", "stdout", "stderr", "fatal"):
            if k in r:
                out[k] = r[k]
    emit(out)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
